### ISSUE TITLE
一个疑问

### ISSUE THREAD

**Issue by hezhongfeng** [zhouzhihu/webapp#1]
你好：
请问build之后，也就是使用webpack打包之后
打包完毕的js和html等文件要如何使用呢？
这里一直不懂
是不是利用服务端开启监听，然后无论什么请求都把这个html返回给浏览器？

**Comment by zhouzhihu** [comment]
Vue借助webpack实现模块化打包及加载，同时提供vue-loader插件可以让开发人员直接在.vue中书写
template、css和js代码。
不是无论什么请求都将html返回浏览器，而是利用vue-router实现页面路由功能，请参考源码src\router\index.js，这里面定义了路由规则。
index.html页面只在第一次访问时加载所需资源，后面点击每个路由加载指定组件资源，
利用chorme开发工具看下就知道了。
